import { signal } from '@angular/core';
import { v4 as uuidv4 } from 'uuid';

export const accountSumSignal = signal(70000); // Initialize account sum

export const mockData: any = [
  {
    id: uuidv4(),
    campaignName: 'Summer Sale Campaign',
    status: 'ON',
    keywords: ['summer', 'sale', 'discount', 'clothing'],
    bidAmount: 1500,
    campaignFund: 10000,
    town: 'Kraków',
    radius: 50,
  },
  {
    id: uuidv4(),
    campaignName: 'New Year Promo',
    status: 'OFF',
    keywords: ['new year', 'promo', 'celebration', 'sale'],
    bidAmount: 1200,
    campaignFund: 5000,
    town: 'Warsaw',
    radius: 30,
  },
  {
    id: uuidv4(),
    campaignName: 'Holiday Special',
    status: 'OFF',
    keywords: ['holiday', 'special', 'discount', 'travel'],
    bidAmount: 2000,
    campaignFund: 15000,
    town: 'Gdańsk',
    radius: 100,
  },
  {
    id: uuidv4(),
    campaignName: 'Winter Gear Promo',
    status: 'ON',
    keywords: ['winter', 'gear', 'clothing', 'sale'],
    bidAmount: 800,
    campaignFund: 6000,
    town: 'Wrocław',
    radius: 20,
  },
  {
    id: uuidv4(),
    campaignName: 'Tech Gadgets Sale',
    status: 'ON',
    keywords: ['tech', 'gadgets', 'electronics', 'sale'],
    bidAmount: 2500,
    campaignFund: 12000,
    town: 'Poznań',
    radius: 40,
  },
  {
    id: uuidv4(),
    campaignName: 'Back to School',
    status: 'ON',
    keywords: ['school', 'stationery', 'back to school', 'discount'],
    bidAmount: 1000,
    campaignFund: 8000,
    town: 'Lublin',
    radius: 60,
  },
  {
    id: uuidv4(),
    campaignName: 'Spring Collection Launch',
    status: 'OFF',
    keywords: ['spring', 'collection', 'fashion', 'launch'],
    bidAmount: 1800,
    campaignFund: 11000,
    town: 'Szczecin',
    radius: 70,
  },
  {
    id: uuidv4(),
    campaignName: 'Summer Sale Campaign',
    status: 'OFF',
    keywords: ['summer', 'sale', 'discount', 'clothing'],
    bidAmount: 1500,
    campaignFund: 10000,
    town: 'Kraków',
    radius: 50,
  },
  {
    id: uuidv4(),
    campaignName: 'New Year Promo',
    status: 'OFF',
    keywords: ['new year', 'promo', 'celebration', 'sale'],
    bidAmount: 1200,
    campaignFund: 5000,
    town: 'Warsaw',
    radius: 30,
  },
  {
    id: uuidv4(),
    campaignName: 'Holiday Special',
    status: 'ON',
    keywords: ['holiday', 'special', 'discount', 'travel'],
    bidAmount: 2000,
    campaignFund: 15000,
    town: 'Gdańsk',
    radius: 100,
  },
  {
    id: uuidv4(),
    campaignName: 'Winter Gear Promo',
    status: 'OFF',
    keywords: ['winter', 'gear', 'clothing', 'sale'],
    bidAmount: 800,
    campaignFund: 6000,
    town: 'Wrocław',
    radius: 20,
  },
  {
    id: uuidv4(),
    campaignName: 'Tech Gadgets Sale',
    status: 'ON',
    keywords: ['tech', 'gadgets', 'electronics', 'sale'],
    bidAmount: 2500,
    campaignFund: 12000,
    town: 'Poznań',
    radius: 40,
  },
  {
    id: uuidv4(),
    campaignName: 'Back to School',
    status: 'OFF',
    keywords: ['school', 'stationery', 'back to school', 'discount'],
    bidAmount: 1000,
    campaignFund: 8000,
    town: 'Lublin',
    radius: 60,
  },
  {
    id: uuidv4(),
    campaignName: 'Spring Collection Launch',
    status: 'ON',
    keywords: ['spring', 'collection', 'fashion', 'launch'],
    bidAmount: 1800,
    campaignFund: 11000,
    town: 'Szczecin',
    radius: 70,
  },
];
